services:
  socket-server:
    build:
      context: .
    container_name: crowd-vision-socket
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - CLIENT_URL=${DEV_URL}:${CLIENT_PORT}
      - GATEWAY_JWKS_URI=http://claims-gateway:3000/.well-known/jwks.json
      - GATEWAY_ISSUER=cv-gateway
    depends_on:
      - redis
