services:
  auth-service:
    build:
      context: .
    environment:
      - MONGO_URI=mongodb://auth-db:27017/authdb
      - JWT_SECRET=${JWT_SECRET}
      - VITE_SERVER_URL=${DEV_URL}:${SERVER_PORT}
      - CLIENT_URL=${DEV_URL}:${CLIENT_PORT}
      - INTERNAL_ADMIN_SECRET=${INTERNAL_ADMIN_SECRET}
    depends_on:
      - auth-db

  auth-db:
    image: mongo:latest
    volumes:
      - auth-data:/data/db

volumes:
  auth-data:
