services:
  sensor-service:
    build:
      context: .
    environment:
      - MONGO_URI=mongodb://sensor-db:27017/sensordb
      - CLIENT_URL=${DEV_URL}:${CLIENT_PORT}
      - VITE_SERVER_URL=http://gateway
      - REDIS_URL=redis://redis:6379
    depends_on:
      - sensor-db

  sensor-db:
    image: mongo:latest
    volumes:
      - sensor-data:/data/db

volumes:
  sensor-data:
