const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = path.join(__dirname, "../..", ".env");

function generateAdminSecret() {
    let envContent = "";

    // Read existing .env; absent file stays empty (no existsSync → no TOCTOU race).
    try {
        envContent = fs.readFileSync(envPath, "utf8");
    } catch (e) {
        if (e.code !== "ENOENT") throw e;
    }

    if (envContent.includes("INTERNAL_ADMIN_SECRET=")) {
        console.log("✅ INTERNAL_ADMIN_SECRET is already present in .env. Skipping generation.");
        return;
    }

    console.log("🔑 Generating secure INTERNAL_ADMIN_SECRET...");
    const generatedSecret = crypto.randomBytes(32).toString("hex");
    const envEntry = `\n# Generated by scripts/env/admin.js\nINTERNAL_ADMIN_SECRET=${generatedSecret}\n`;

    // appendFileSync creates the file if absent, so no existence check (avoids a TOCTOU race).
    fs.appendFileSync(envPath, envEntry);

    console.log("✅ Secret generated and appended to .env");
    console.log("⚠️  IMPORTANT: Please RESTART your server now so it loads the new secret!");
}

generateAdminSecret();
