const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = path.join(__dirname, "../..", ".env");

// Secrets the Go control plane needs to boot: INTERNAL_SIGNING_SECRET is the shared
// HMAC key for their system-to-system calls; *_DB_PASSWORD back their Postgres instances.
function generateControlPlaneSecrets() {
    let envContent = "";

    try {
        envContent = fs.readFileSync(envPath, "utf8");
    } catch (e) {
        if (e.code !== "ENOENT") throw e;
    }

    if (envContent.includes("INTERNAL_SIGNING_SECRET=")) {
        console.log("✅ Control-plane secrets already present in .env. Skipping generation.");
        return;
    }

    console.log("🔑 Generating control-plane dev secrets...");
    const signingSecret = crypto.randomBytes(32).toString("hex");
    const tenancyDbPassword = crypto.randomBytes(16).toString("hex");
    const registryDbPassword = crypto.randomBytes(16).toString("hex");
    const envEntry =
        `\n# Generated by scripts/env/controlplane.js\n` +
        `INTERNAL_SIGNING_SECRET=${signingSecret}\n` +
        `TENANCY_DB_PASSWORD=${tenancyDbPassword}\n` +
        `REGISTRY_DB_PASSWORD=${registryDbPassword}\n`;

    fs.appendFileSync(envPath, envEntry);

    console.log("✅ Control-plane secrets generated and appended to .env");
}

generateControlPlaneSecrets();
