#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

if env_has "INTERNAL_SIGNING_SECRET="; then
    exit 0
fi

echo "🔑 Generating control-plane dev secrets..."

env_append <<EOF

# Generated by scripts/env/controlplane.sh
INTERNAL_SIGNING_SECRET=$(hex 32)
TENANCY_DB_PASSWORD=$(hex 16)
REGISTRY_DB_PASSWORD=$(hex 16)
EOF

echo "✅ Control-plane secrets generated and appended to .env"
