#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

if env_has "TELEMETRY_INGEST_SECRET="; then
    exit 0
fi

echo "🔑 Generating telemetry ingest secret..."

env_append <<EOF

# Generated by scripts/env/ingest-key.sh
TELEMETRY_INGEST_SECRET=$(hex 32)
EOF

echo "✅ Telemetry ingest secret generated and appended to .env"
