#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

# The shared key signs for any building: dev and simulators only. Production leaves it unset.
if ! env_has "TELEMETRY_INGEST_SECRET="; then
    echo "🔑 Generating telemetry ingest secret..."
    env_append <<EOT

# Generated by scripts/env/ingest-key.sh
TELEMETRY_INGEST_SECRET=$(hex 32)
EOT
fi

# Every building's device key is derived from this one; losing it revokes them all.
if ! env_has "TELEMETRY_DEVICE_MASTER_KEY="; then
    echo "🔑 Generating telemetry device master key..."
    env_append <<EOT

# Generated by scripts/env/ingest-key.sh
TELEMETRY_DEVICE_MASTER_KEY=$(hex 32)
EOT
fi
