const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = path.join(__dirname, "../..", ".env");

// Shared HMAC key a gateway signs telemetry bodies with. Distinct from
// INTERNAL_SIGNING_SECRET: this one leaves the mesh and lives on customer
// premises, so it must never unlock the control plane.
function generateIngestSecret() {
    let envContent = "";

    try {
        envContent = fs.readFileSync(envPath, "utf8");
    } catch (e) {
        if (e.code !== "ENOENT") throw e;
    }

    if (envContent.includes("TELEMETRY_INGEST_SECRET=")) {
        console.log("✅ Telemetry ingest secret already present in .env. Skipping generation.");
        return;
    }

    console.log("🔑 Generating telemetry ingest secret...");
    const secret = crypto.randomBytes(32).toString("hex");
    const envEntry =
        `\n# Generated by scripts/env/ingest-key.js\n` + `TELEMETRY_INGEST_SECRET=${secret}\n`;

    fs.appendFileSync(envPath, envEntry);

    console.log("✅ Telemetry ingest secret generated and appended to .env");
}

generateIngestSecret();
