#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

if env_has "KEYCLOAK_ADMIN_PASSWORD="; then
    exit 0
fi

echo "🔑 Generating Keycloak dev secrets..."

env_append <<EOF

# Generated by scripts/env/keycloak.sh
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASSWORD=$(hex 16)
KEYCLOAK_DB_PASSWORD=$(hex 16)
# Google social login (optional). Create an OAuth 2.0 client in Google
# Cloud Console, then paste its id/secret here to enable the
# "Continue with Google" button. See keycloak/README-google.md.
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
EOF

echo "✅ Keycloak secrets generated and appended to .env"
