const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = path.join(__dirname, "../..", ".env");

function generateKeycloakSecrets() {
    let envContent = "";

    try {
        envContent = fs.readFileSync(envPath, "utf8");
    } catch (e) {
        if (e.code !== "ENOENT") throw e;
    }

    if (envContent.includes("KEYCLOAK_ADMIN_PASSWORD=")) {
        console.log("✅ Keycloak secrets already present in .env. Skipping generation.");
        return;
    }

    console.log("🔑 Generating Keycloak dev secrets...");
    const adminPassword = crypto.randomBytes(16).toString("hex");
    const dbPassword = crypto.randomBytes(16).toString("hex");
    const envEntry =
        `\n# Generated by scripts/env/keycloak.js\n` +
        `KEYCLOAK_ADMIN_USER=admin\n` +
        `KEYCLOAK_ADMIN_PASSWORD=${adminPassword}\n` +
        `KEYCLOAK_DB_PASSWORD=${dbPassword}\n` +
        `# Google social login (optional). Create an OAuth 2.0 client in Google\n` +
        `# Cloud Console, then paste its id/secret here to enable the\n` +
        `# "Continue with Google" button. See keycloak/README-google.md.\n` +
        `GOOGLE_CLIENT_ID=\n` +
        `GOOGLE_CLIENT_SECRET=\n`;

    fs.appendFileSync(envPath, envEntry);

    console.log("✅ Keycloak secrets generated and appended to .env");
}

generateKeycloakSecrets();
