const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = path.join(__dirname, "../..", ".env");

function generateKeycloakSecrets() {
    let envContent = "";

    try {
        envContent = fs.readFileSync(envPath, "utf8");
    } catch (e) {
        if (e.code !== "ENOENT") throw e;
    }

    if (envContent.includes("KEYCLOAK_ADMIN_PASSWORD=")) {
        console.log("✅ Keycloak secrets already present in .env. Skipping generation.");
        return;
    }

    console.log("🔑 Generating Keycloak dev secrets...");
    const adminPassword = crypto.randomBytes(16).toString("hex");
    const dbPassword = crypto.randomBytes(16).toString("hex");
    const envEntry = `\n# Generated by scripts/env/keycloak.js\nKEYCLOAK_ADMIN_USER=admin\nKEYCLOAK_ADMIN_PASSWORD=${adminPassword}\nKEYCLOAK_DB_PASSWORD=${dbPassword}\n`;

    fs.appendFileSync(envPath, envEntry);

    console.log("✅ Keycloak secrets generated and appended to .env");
}

generateKeycloakSecrets();
