// Auto-generates the self-hosted Langfuse secrets and the OpenTelemetry exporter
// config the agent-service uses to ship traces to Langfuse. Mirrors token.js /
// admin.js: idempotent (skips if already present), appends a commented block.
//
// The project + API keys are provisioned headlessly by Langfuse on first boot from
// these LANGFUSE_INIT_* / LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY values, and the
// agent authenticates to Langfuse's OTLP endpoint with the same key pair.

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = process.env.ENV_FILE || path.join(__dirname, "../..", ".env");
const currentEnv = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";

if (currentEnv.includes("LANGFUSE_PUBLIC_KEY")) {
    console.log("✅ Langfuse / OTEL config already present in .env. Skipping generation.");
    process.exit(0);
}

console.log("🔑 Generating Langfuse secrets + OpenTelemetry exporter config...");

const hex = (bytes) => crypto.randomBytes(bytes).toString("hex");
const publicKey = `pk-lf-${hex(16)}`;
const secretKey = `sk-lf-${hex(16)}`;

// OTLP/HTTP Basic-auth header for Langfuse, URL-encoded for the
// OTEL_EXPORTER_OTLP_HEADERS format (space -> %20, base64 +/= -> %2B/%2F/%3D).
const basic = Buffer.from(`${publicKey}:${secretKey}`).toString("base64");
const otelHeader = `Authorization=${encodeURIComponent(`Basic ${basic}`)}`;

const block = `
# ── Langfuse (LLM observability) — auto-generated by scripts/env/langfuse.js ──
# Self-hosted Langfuse v3 (see docker-compose.yml). UI: http://localhost:3030
# (or http://localhost/langfuse). Log in with the LANGFUSE_INIT_USER_* creds; the
# project + API keys are provisioned headlessly on first boot. ENCRYPTION_KEY must
# be 64 hex chars. Rotate all of these for any non-local deployment.
LANGFUSE_PUBLIC_KEY=${publicKey}
LANGFUSE_SECRET_KEY=${secretKey}
LANGFUSE_INIT_ORG_ID=crowd-vision
LANGFUSE_INIT_ORG_NAME=Crowd-Vision
LANGFUSE_INIT_PROJECT_ID=agent-service
LANGFUSE_INIT_PROJECT_NAME=agent-service
LANGFUSE_INIT_USER_EMAIL=admin@crowd-vision.local
LANGFUSE_INIT_USER_NAME=Admin
LANGFUSE_INIT_USER_PASSWORD=langfuse-admin
LANGFUSE_SALT=${hex(16)}
LANGFUSE_ENCRYPTION_KEY=${hex(32)}
LANGFUSE_NEXTAUTH_SECRET=${hex(16)}
LANGFUSE_CLICKHOUSE_PASSWORD=${hex(12)}
LANGFUSE_MINIO_ROOT_PASSWORD=${hex(12)}

# ── OpenTelemetry → Langfuse (agent-service exporter) ─────────────────────────
# Unset OTEL_EXPORTER_OTLP_ENDPOINT to fall back to compact console span output
# (no trace backend required for local hacking).
OTEL_EXPORTER_OTLP_ENDPOINT=http://langfuse-web:3000/api/public/otel
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_HEADERS=${otelHeader}
`;

// appendFileSync creates the file if absent, so no existence check (avoids a TOCTOU race).
fs.appendFileSync(envPath, block);

console.log("✅ Langfuse + OTEL config appended to .env");
console.log("   Langfuse UI: http://localhost:3030  (login: admin@crowd-vision.local / langfuse-admin)");
