#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

if env_has "LANGFUSE_PUBLIC_KEY"; then
    exit 0
fi

echo "🔑 Generating Langfuse secrets + OpenTelemetry exporter config..."

public_key="pk-lf-$(hex 16)"
secret_key="sk-lf-$(hex 16)"
basic=$(printf '%s:%s' "$public_key" "$secret_key" | base64 | tr -d '\n')
otel_header="Authorization=Basic%20$(printf '%s' "$basic" | sed 's/+/%2B/g; s|/|%2F|g; s/=/%3D/g')"

env_append <<EOF

# ── Langfuse (LLM observability) — auto-generated by scripts/env/langfuse.sh ──
# Self-hosted Langfuse v3 (see docker-compose.yml). UI: http://localhost:3030
# (or http://localhost/langfuse). Log in with the LANGFUSE_INIT_USER_* creds; the
# project + API keys are provisioned headlessly on first boot. ENCRYPTION_KEY must
# be 64 hex chars. Rotate all of these for any non-local deployment.
LANGFUSE_PUBLIC_KEY=$public_key
LANGFUSE_SECRET_KEY=$secret_key
LANGFUSE_INIT_ORG_ID=crowd-vision
LANGFUSE_INIT_ORG_NAME=Crowd-Vision
LANGFUSE_INIT_PROJECT_ID=agent-service
LANGFUSE_INIT_PROJECT_NAME=agent-service
LANGFUSE_INIT_USER_EMAIL=admin@crowd-vision.local
LANGFUSE_INIT_USER_NAME=Admin
LANGFUSE_INIT_USER_PASSWORD=langfuse-admin
LANGFUSE_SALT=$(hex 16)
LANGFUSE_ENCRYPTION_KEY=$(hex 32)
LANGFUSE_NEXTAUTH_SECRET=$(hex 16)
LANGFUSE_CLICKHOUSE_PASSWORD=$(hex 12)
LANGFUSE_MINIO_ROOT_PASSWORD=$(hex 12)

# ── OpenTelemetry → Langfuse (agent-service exporter) ─────────────────────────
# Unset OTEL_EXPORTER_OTLP_ENDPOINT to fall back to compact console span output
# (no trace backend required for local hacking).
OTEL_EXPORTER_OTLP_ENDPOINT=http://langfuse-web:3000/api/public/otel
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_HEADERS=$otel_header
EOF

echo "✅ Langfuse + OTEL config appended to .env"
echo "   Langfuse UI: http://localhost:3030  (login: admin@crowd-vision.local / langfuse-admin)"
