#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

# Rewritten every run, not written once: a bump in .mise.toml must reach the Docker
# build arg, or a stale .env pins the image to the previous compiler in silence.
version=$(sed -n 's/^rust = "\(.*\)"$/\1/p' "$ROOT/.mise.toml")
if [ -z "$version" ]; then
    echo "rust pin not found in .mise.toml" >&2
    exit 1
fi

if env_key_set RUST_VERSION; then
    sed -i "s|^[[:space:]]*RUST_VERSION[[:space:]]*=.*|RUST_VERSION=$version|" "$ENV_PATH"
else
    env_append <<EOF

# Generated by scripts/env/rust.sh — mirrors the rust pin in .mise.toml
RUST_VERSION=$version
EOF
fi

echo "✅ RUST_VERSION=$version written to .env"
