#!/bin/sh
set -eu
. "$(dirname -- "$0")/lib.sh"

if env_has "TELEMETRY_DB_PASSWORD="; then
    exit 0
fi

echo "🔑 Generating telemetry DB password..."

env_append <<EOF

# Generated by scripts/env/telemetry-db.sh
TELEMETRY_DB_PASSWORD=$(hex 16)
EOF

echo "✅ Telemetry DB password generated and appended to .env"
