services:
  claims-gateway:
    build:
      target: dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O", "/dev/null", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/server/claims-gateway
        - action: rebuild
          path: ./go.mod
