services:
  auth-service:
    build:
      context: ./server/auth-service
      target: builder
    command: npm run dev
    environment:
      - MONGO_URI=mongodb://auth-db:27017/authdb
    networks:
      - gateway-net
      - auth-net
    develop:
      watch:
        - action: sync
          path: ./server/auth-service/src
          target: /app/src
        - action: rebuild
          path: ./server/auth-service/package.json

  twin-service:
    build:
      context: ./server/twin-service
      target: builder
    command: npm run dev
    environment:
      - MONGO_URI=mongodb://twin-db:27017/twindb
      - SENSOR_SERVICE_URL=http://sensor-service:3000
    networks:
      - gateway-net
      - twin-net
    develop:
      watch:
        - action: sync
          path: ./server/twin-service/src
          target: /app/src
        - action: rebuild
          path: ./server/twin-service/package.json

  twin-db:
    ports:
      - "27017:27017"

  sensor-db:
    ports:
      - "27018:27017"

  notification-service:
    build:
      context: ./server/notification-service
      target: builder
    command: npm run dev
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://notification-db:27017/notificationdb
      - VITE_SERVER_URL=http://gateway
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    depends_on:
      - redis
    networks:
      - gateway-net
      - notification-net
    develop:
      watch:
        - action: sync
          path: ./server/notification-service/src
          target: /app/src
        - action: rebuild
          path: ./server/notification-service/package.json

  agent-service:
    build:
      context: ./server/agent-service
    command: npm run dev
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - TWIN_SERVICE_URL=http://twin-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    networks:
      - gateway-net
      - twin-net
      - auth-net
    develop:
      watch:
        - action: sync
          path: ./server/agent-service/src
          target: /app/src
        - action: rebuild
          path: ./server/agent-service/package.json

  client:
    container_name: vue-client
    build:
      context: ./client
      target: build-stage
      args:
        VITE_SERVER_URL: ${DEV_URL}:${SERVER_PORT}
        VITE_VAPID_PUBLIC_KEY: ${VITE_VAPID_PUBLIC_KEY}
    ports:
      - "${CLIENT_PORT}:8080"
    environment:
      - PORT=${CLIENT_PORT}
    command: npm run dev -- --host --port 8080
    networks:
      - gateway-net
    depends_on:
      - auth-service
      - gateway
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
