services:
  gateway:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - gateway-net
    depends_on:
      - auth-service
      - twin-service
      - simulator-service
      - sensor-service
      - socket-server

  redis:
    image: redis:alpine
    container_name: crowd-vision-broker
    ports:
      - "6379:6379"
    networks:
      - gateway-net

networks:
  gateway-net:
    driver: bridge
  auth-net:
  twin-net:
  simulator-net:
  sensor-net:  
  notification-net:

volumes:
  caddy_data:
  caddy_config:

