services:
  auth-db-express:
    image: mongo-express:latest
    profiles:
      - dev
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://auth-db:27017/
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_SITE_BASEURL=/auth-db-gui/
    networks:
      - gateway-net
      - auth-net
    depends_on:
      - auth-db

  twin-db-express:
    image: mongo-express
    profiles:
      - dev
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://twin-db:27017/
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_SITE_BASEURL=/twin-db-gui/
    networks:
      - gateway-net
      - twin-net
    depends_on:
      - twin-db

  sensor-db-express:
    image: mongo-express
    profiles:
      - dev
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://sensor-db:27017/
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_SITE_BASEURL=/sensor-db-gui/
    networks:
      - gateway-net
      - sensor-net
    depends_on:
      - sensor-db

