#!/usr/bin/env python3
"""Docker Compose orchestrator: writes compose.runtime.yml listing kept service
files under `include:` (resolves build.context per-file, unlike -f)."""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

RUNTIME_FILE = "compose.runtime.yml"
MODES = ("dev", "start", "down", "build")
EXCLUDE_GROUPS = {
    "agent": ("agent",),
    "metrics": ("prometheus", "grafana"),
    "simulators": ("simulator",),
}

parser = argparse.ArgumentParser(prog="just stack <mode>", description=__doc__)
parser.add_argument("mode", nargs="?", default="dev", choices=MODES)
parser.add_argument(
    "patterns",
    nargs="*",
    metavar="PATTERN",
    help="folder or service name substring to exclude",
)
for group, members in EXCLUDE_GROUPS.items():
    parser.add_argument(
        f"--no-{group}", action="store_true", help=f"exclude {', '.join(members)}"
    )
parser.add_argument("--build", action="store_true", help="rebuild images before starting")
parser.add_argument(
    "--dry-run", action="store_true", help="print the docker command and exit"
)
args = parser.parse_args()

requested = list(args.patterns) + [
    group for group in EXCLUDE_GROUPS if getattr(args, f"no_{group}")
]
exclude_patterns = [
    expanded
    for raw in requested
    for pattern in re.sub(r"^exclude=", "", raw).split()
    for expanded in EXCLUDE_GROUPS.get(pattern, (pattern,))
]

mode = args.mode
is_dev = mode == "dev"
effective_excludes = [] if mode in ("down", "build") else exclude_patterns


def is_excluded(name):
    return any(pattern in name for pattern in effective_excludes)


includes = []


def add_include(path):
    includes.append([path])


def add_service(folder, with_dev):
    paths = []
    if Path(folder, "docker-compose.yml").exists():
        paths.append(f"{folder}/docker-compose.yml")
    if with_dev and Path(folder, "docker-compose.dev.yml").exists():
        paths.append(f"{folder}/docker-compose.dev.yml")
    if paths:
        includes.append(paths)


def iterate(parent, skip=()):
    if not Path(parent).exists():
        return
    for folder in sorted(os.listdir(parent)):
        full = f"{parent}/{folder}"
        if not Path(full).is_dir() or folder in skip:
            continue
        if is_excluded(folder):
            print(f"  excluded: {parent}/{folder}")
            continue
        add_service(full, is_dev)


add_include("docker-compose.yml")
iterate("backend", skip=("tests",))
iterate("simulators")

if not is_excluded("frontend"):
    add_service("frontend", is_dev)
lines = [
    "# Auto-generated by scripts/compose/compose-run.py — do not commit.",
    "# Re-generated every time `just stack dev` / `just stack start` / `just stack down` runs.",
    "include:",
]
for paths in includes:
    if len(paths) == 1:
        lines.append(f"  - path: {paths[0]}")
    else:
        lines.append("  - path:")
        lines.extend(f"      - {path}" for path in paths)
Path(RUNTIME_FILE).write_text("\n".join(lines) + "\n")

config = subprocess.run(
    ["docker", "compose", "-f", RUNTIME_FILE, "config", "--format", "json"],
    capture_output=True,
    text=True,
)
if config.returncode == 0:
    services = json.loads(config.stdout).get("services") or {}
    names = {s["container_name"] for s in services.values() if s.get("container_name")}
    listed = subprocess.run(
        ["docker", "ps", "-a", "--format", "{{.Names}}\t{{.State}}"],
        capture_output=True,
        text=True,
    )
    strays = []
    for line in (listed.stdout or "").splitlines():
        name, _, state = line.partition("\t")
        if name in names and state != "running":
            strays.append(name)
    if strays:
        print(f"Removing stray containers: {', '.join(strays)}")
        subprocess.run(["docker", "rm", "-f", *strays])

if mode == "down":
    docker_args = ["compose", "-f", RUNTIME_FILE, "down", "--remove-orphans"]
elif mode == "build":
    docker_args = ["compose", "-f", RUNTIME_FILE, "build"]
elif mode == "start":
    docker_args = ["compose", "-f", RUNTIME_FILE, "up", "--build", "-d", "--remove-orphans"]
else:
    docker_args = ["compose", "-f", RUNTIME_FILE, "up", "--watch", "--remove-orphans"]
    if args.build:
        docker_args.append("--build")

if effective_excludes and mode in ("dev", "start"):
    listed = subprocess.run(
        ["docker", "compose", "-f", RUNTIME_FILE, "config", "--services"],
        capture_output=True,
        text=True,
    )
    kept = [name for name in listed.stdout.split() if not is_excluded(name)]
    dropped = [name for name in listed.stdout.split() if is_excluded(name)]
    if kept:
        docker_args.extend(kept)
    if dropped:
        print(f"Excluded services: {', '.join(dropped)}")

print(f"Generated {RUNTIME_FILE} with {len(includes)} includes.")
print(f"\n$ docker {' '.join(docker_args)}\n")

if args.dry_run:
    sys.exit(0)

try:
    result = subprocess.run(["docker", *docker_args], env={**os.environ, "COMPOSE_BAKE": "true"})
except KeyboardInterrupt:
    sys.exit(130)
sys.exit(result.returncode if result.returncode >= 0 else 1)
