//
// Cross-platform Docker Compose orchestrator.
//
// Strategy:
//   1. Walk the service folders, filter by exclude patterns.
//   2. Write a runtime compose file (compose.runtime.yml) that lists the kept
//      compose files inside an `include:` block.
//   3. Run `docker compose -f compose.runtime.yml ...`.
//
// Why a generated file with `include:`?
//   - Passing multiple `-f` files makes Docker Compose resolve relative paths
//     (like `build.context: .`) relative to the FIRST file's directory.
//     That breaks per-service Dockerfile lookups.
//   - `include:` instead resolves paths relative to each included file, so
//     `build.context: .` in server/twin-service/docker-compose.yml correctly
//     points at server/twin-service/.

import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, sep } from "node:path";

// ── Parse arguments ──────────────────────────────────────────────────────────

const [, , mode = "dev", ...rawExcludes] = process.argv;

// Accept both `just dev "agent simulator"` (positional) and
// `just dev exclude="agent simulator"` (named — Just may pass through as
// the literal `exclude=...`). Strip the prefix if present, then split on
// whitespace so a single quoted multi-word arg expands cleanly.
const excludePatterns = rawExcludes
  .flatMap((arg) => arg.replace(/^exclude=/, "").split(/\s+/))
  .filter(Boolean);

const isDev = mode === "dev" || mode === "dev-build";
const isStart = mode === "start";
const isDown = mode === "down";
const isIntegration = mode === "integration";
const isBuild = mode === "build";
const isDevBuild = mode === "dev-build";

if (!isDev && !isStart && !isDown && !isIntegration && !isBuild && !isDevBuild) {
  console.error(
    `Unknown mode: ${mode}. Use: dev | start | down | integration | build | dev-build`,
  );
  process.exit(1);
}

// down/integration/build always include everything — ignore any patterns passed
const effectiveExcludes =
  isDown || isIntegration || isBuild ? [] : excludePatterns;
const isExcluded = (name) =>
  effectiveExcludes.some((pat) => name.includes(pat));

// ── Build the include list ───────────────────────────────────────────────────

const norm = (p) => p.split(sep).join("/");

// Each entry is an array of paths: a single-path entry becomes one sub-project,
// a multi-path entry merges base + override into one sub-project (Compose's
// `include: - path: [a, b]` form). Two separate include entries cannot define
// the same service — that triggers "conflicts with imported resource".
const includes = [];
const addInclude = (path) => includes.push([norm(path)]);

const addService = (folderPath, withDev) => {
  const base = join(folderPath, "docker-compose.yml");
  const dev = join(folderPath, "docker-compose.dev.yml");
  const paths = [];
  if (existsSync(base)) paths.push(norm(base));
  if (withDev && existsSync(dev)) paths.push(norm(dev));
  if (paths.length) includes.push(paths);
};

const iterate = (parent, { skip = [] } = {}) => {
  if (!existsSync(parent)) return;
  for (const folder of readdirSync(parent)) {
    const full = join(parent, folder);
    if (!statSync(full).isDirectory()) continue;
    if (skip.includes(folder)) continue;
    if (isExcluded(folder)) {
      console.log(`  excluded: ${parent}/${folder}`);
      continue;
    }
    addService(full, isDev);
  }
};

addInclude("docker-compose.yml");
iterate("server", { skip: ["tests"] });
iterate("simulators");

if (!isExcluded("client")) {
  addService("client", isDev);
}
if (isIntegration) {
  addInclude("server/tests/docker-compose.integration.yml");
}

// ── Write the runtime compose file ───────────────────────────────────────────

const RUNTIME_FILE = "compose.runtime.yml";
const runtimeYaml =
  `# Auto-generated by scripts/compose/compose-run.mjs — do not commit.\n` +
  `# Re-generated every time \`just dev\` / \`just start\` / \`just down\` runs.\n` +
  `include:\n` +
  includes
    .map((paths) =>
      paths.length === 1
        ? `  - path: ${paths[0]}`
        : `  - path:\n${paths.map((p) => `      - ${p}`).join("\n")}`,
    )
    .join("\n") +
  `\n`;

writeFileSync(RUNTIME_FILE, runtimeYaml);

// ── Build and run the docker command ─────────────────────────────────────────

let dockerArgs;
if (isDown) {
  dockerArgs = ["compose", "-f", RUNTIME_FILE, "down", "--remove-orphans"];
} else if (isBuild) {
  dockerArgs = ["compose", "-f", RUNTIME_FILE, "build"];
} else if (isIntegration) {
  dockerArgs = [
    "compose",
    "-f",
    RUNTIME_FILE,
    "up",
    "--build",
    "--exit-code-from",
    "integration-tests",
    "--abort-on-container-exit",
  ];
} else if (isStart) {
  dockerArgs = ['compose', '-f', RUNTIME_FILE, 'up', '--build', '-d', '--remove-orphans'];
} else {
  // dev
  dockerArgs = ['compose', '-f', RUNTIME_FILE, 'up', '--watch', '--remove-orphans'];
  if (isDevBuild) dockerArgs.push("--build");
}

if (effectiveExcludes.length > 0) {
  console.log(`Exclude patterns: ${effectiveExcludes.join(", ")}`);
}
console.log(`Generated ${RUNTIME_FILE} with ${includes.length} includes.`);
console.log(`\n$ docker ${dockerArgs.join(" ")}\n`);

const result = spawnSync("docker", dockerArgs, {
  stdio: "inherit",
  shell: false,
  env: { ...process.env, COMPOSE_BAKE: "true" },
});

process.exit(result.status ?? 1);
