// Cross-platform Docker Compose orchestrator: writes compose.runtime.yml listing
// kept service files under `include:` (resolves build.context per-file, unlike -f).

import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, sep } from "node:path";

// ── Parse arguments ──────────────────────────────────────────────────────────

const [, , mode = "dev", ...rawExcludes] = process.argv;

// Accept positional (`dev "agent simulator"`) or named (`dev exclude="..."`) forms:
// strip any `exclude=` prefix, then split on whitespace to expand quoted multi-word args.
const excludePatterns = rawExcludes
  .flatMap((arg) => arg.replace(/^exclude=/, "").split(/\s+/))
  .filter(Boolean);

const isDev = mode === "dev" || mode === "dev-build";
const isStart = mode === "start";
const isDown = mode === "down";
const isIntegration = mode === "integration";
const isBuild = mode === "build";
const isDevBuild = mode === "dev-build";

if (!isDev && !isStart && !isDown && !isIntegration && !isBuild && !isDevBuild) {
  console.error(
    `Unknown mode: ${mode}. Use: dev | start | down | integration | build | dev-build`,
  );
  process.exit(1);
}

// down/integration/build always include everything — ignore any patterns passed
const effectiveExcludes =
  isDown || isIntegration || isBuild ? [] : excludePatterns;
const isExcluded = (name) =>
  effectiveExcludes.some((pat) => name.includes(pat));

// ── Build the include list ───────────────────────────────────────────────────

const norm = (p) => p.split(sep).join("/");

// Each entry is a path array: one path = one sub-project, multiple = base+override
// merged. Separate entries can't share a service ("conflicts with imported resource").
const includes = [];
const addInclude = (path) => includes.push([norm(path)]);

const addService = (folderPath, withDev) => {
  const base = join(folderPath, "docker-compose.yml");
  const dev = join(folderPath, "docker-compose.dev.yml");
  const paths = [];
  if (existsSync(base)) paths.push(norm(base));
  if (withDev && existsSync(dev)) paths.push(norm(dev));
  if (paths.length) includes.push(paths);
};

const iterate = (parent, { skip = [] } = {}) => {
  if (!existsSync(parent)) return;
  for (const folder of readdirSync(parent)) {
    const full = join(parent, folder);
    if (!statSync(full).isDirectory()) continue;
    if (skip.includes(folder)) continue;
    if (isExcluded(folder)) {
      console.log(`  excluded: ${parent}/${folder}`);
      continue;
    }
    addService(full, isDev);
  }
};

addInclude("docker-compose.yml");
iterate("server", { skip: ["tests"] });
iterate("simulators");

if (!isExcluded("client")) {
  addService("client", isDev);
}
if (isIntegration) {
  addInclude("server/tests/docker-compose.integration.yml");
}

// ── Write the runtime compose file ───────────────────────────────────────────

const RUNTIME_FILE = "compose.runtime.yml";
const runtimeYaml =
  `# Auto-generated by scripts/compose/compose-run.mjs — do not commit.\n` +
  `# Re-generated every time \`just stack dev\` / \`just stack start\` / \`just stack down\` runs.\n` +
  `include:\n` +
  includes
    .map((paths) =>
      paths.length === 1
        ? `  - path: ${paths[0]}`
        : `  - path:\n${paths.map((p) => `      - ${p}`).join("\n")}`,
    )
    .join("\n") +
  `\n`;

writeFileSync(RUNTIME_FILE, runtimeYaml);

// ── Clear stray fixed-name containers ────────────────────────────────────────
// A pinned `container_name:` orphaned by an interrupted run name-clashes the next
// `up` (no compose project label to reconcile it), so force-remove non-running matches.
const cfg = spawnSync(
  "docker",
  ["compose", "-f", RUNTIME_FILE, "config", "--format", "json"],
  { encoding: "utf8" },
);
if (cfg.status === 0) {
  const names = new Set(
    Object.values(JSON.parse(cfg.stdout).services ?? {})
      .map((s) => s.container_name)
      .filter(Boolean),
  );
  const ps = spawnSync(
    "docker",
    ["ps", "-a", "--format", "{{.Names}}\t{{.State}}"],
    { encoding: "utf8" },
  );
  const strays = (ps.stdout ?? "")
    .split(/\r?\n/)
    .map((line) => line.split("\t"))
    .filter(([name, state]) => names.has(name) && state !== "running")
    .map(([name]) => name);
  if (strays.length) {
    console.log(`Removing stray containers: ${strays.join(", ")}`);
    spawnSync("docker", ["rm", "-f", ...strays], { stdio: "inherit" });
  }
}

// ── Build and run the docker command ─────────────────────────────────────────

// The Langfuse/ClickHouse/MinIO stack (root docker-compose.yml) only exists to trace
// agent-service, so it's opted out the same way as excluding the agent-service folder.
const agentProfileArgs = isExcluded("agent") ? [] : ["--profile", "agent"];

let dockerArgs;
if (isDown) {
  dockerArgs = ["compose", ...agentProfileArgs, "-f", RUNTIME_FILE, "down", "--remove-orphans"];
} else if (isBuild) {
  dockerArgs = ["compose", ...agentProfileArgs, "-f", RUNTIME_FILE, "build"];
} else if (isIntegration) {
  dockerArgs = [
    "compose",
    ...agentProfileArgs,
    "-f",
    RUNTIME_FILE,
    "up",
    "--build",
    "--exit-code-from",
    "integration-tests",
    "--abort-on-container-exit",
  ];
} else if (isStart) {
  dockerArgs = ['compose', ...agentProfileArgs, '-f', RUNTIME_FILE, 'up', '--build', '-d', '--remove-orphans'];
} else {
  // dev
  dockerArgs = ['compose', ...agentProfileArgs, '-f', RUNTIME_FILE, 'up', '--watch', '--remove-orphans'];
  if (isDevBuild) dockerArgs.push("--build");
}

if (effectiveExcludes.length > 0) {
  console.log(`Exclude patterns: ${effectiveExcludes.join(", ")}`);
}
console.log(`Generated ${RUNTIME_FILE} with ${includes.length} includes.`);
console.log(`\n$ docker ${dockerArgs.join(" ")}\n`);

const result = spawnSync("docker", dockerArgs, {
  stdio: "inherit",
  shell: false,
  env: { ...process.env, COMPOSE_BAKE: "true" },
});

process.exit(result.status ?? 1);
