services:
  aq-simulator:
    cpus: "3"
    build:
      context: .
    environment:
      - TELEMETRY_INGEST_SECRET=${TELEMETRY_INGEST_SECRET}
      - TELEMETRY_INGEST_URL=http://gateway/telemetry/ingest
    ports:
      - "3002:3000"
