name: Discovery Template

on:
  workflow_call:
    inputs:
      services_json:
        required: true
        type: string
    outputs:
      matrix:
        description: 'filtered matrix in JSON format'
        value: ${{ jobs.filter.outputs.matrix }}
      is_empty:
        description: 'boolean to know if the matrix is empty'
        value: ${{ jobs.filter.outputs.is_empty }}

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
      is_empty: ${{ steps.generate.outputs.is_empty }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24d32ffd492484c1d75e0c0b894501ddb9d30d62

      - name: Generate Dynamic Matrix
        id: generate
        shell: bash
        env:
          ALL_SERVICES: ${{ inputs.services_json }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          MATRIX_JSON=$(echo "$ALL_SERVICES" | jq -c --arg changed "$CHANGED_FILES" 'map(select($changed | contains(.dir)))')
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          if [ "$MATRIX_JSON" = "[]" ]; then
            echo "is_empty=true" >> $GITHUB_OUTPUT
          else
            echo "is_empty=false" >> $GITHUB_OUTPUT
          fi
