#!/usr/bin/env bash
# Composes only what this suite actually touches — telemetry,
# socket, dashboard, plus their own shared infra
# (redis, kafka; docker-compose.infra.yml in this folder) — instead of the
# monorepo's whole stack. Own compose project name, so it never collides
# with a `just stack dev` run and cleans up independently of it.
set -uo pipefail

# Matches scripts/compose/compose-run.py: without this, compose's classic
# build path resolves the podman API socket differently under this
# environment's docker-compose shim and fails to connect.
export COMPOSE_BAKE=true

cd "$(dirname "${BASH_SOURCE[0]}")/../.."  # repo root

# telemetry refuses to boot without an ingest signing key, and both it
# and the test client read the same one out of the repo-root .env that compose
# auto-loads. Generating it here keeps the suite runnable without `just stack env`.
mise exec -- sh scripts/env/ingest-key.sh || {
  echo "::error::could not generate TELEMETRY_INGEST_SECRET" >&2
  exit 1
}

PROJECT_NAME="crowdvision-integration-tests"
RUNTIME_FILE="compose.integration-tests.runtime.yml"

# `include:`, not chained `-f -f -f`: each fragment's own relative
# `build.context` must resolve against ITS OWN directory, and (per
# scripts/compose/compose-run.py's own header comment) chained `-f` doesn't
# reliably do that across this repo's compose fragments — `include:` does.
cat > "$RUNTIME_FILE" <<EOF
# Auto-generated by backend/acceptance/run-integration-tests.sh — do not commit.
include:
  - path: backend/acceptance/docker-compose.infra.yml
  - path: backend/telemetry/docker-compose.yml
  - path: backend/socket/docker-compose.yml
  - path: backend/dashboard/docker-compose.yml
  - path: backend/acceptance/docker-compose.integration.yml
EOF

COMPOSE=(docker compose -p "$PROJECT_NAME" -f "$RUNTIME_FILE")

# socket pins a fixed container_name (crowd-vision-socket, shared
# with the main dev stack) — only remove a leftover if it's confirmed
# stopped, never a container that's part of a live `just stack dev` run.
if [ "$(docker inspect -f '{{.State.Running}}' crowd-vision-socket 2>/dev/null)" = "false" ]; then
  docker rm -f crowd-vision-socket
fi

echo "Generated $RUNTIME_FILE"
echo

"${COMPOSE[@]}" up --build --exit-code-from integration-tests --abort-on-container-exit
exit_code=$?

"${COMPOSE[@]}" down --remove-orphans --volumes

exit "$exit_code"
