services:
  telemetry-service:
    build:
      target: dev
    command: cargo watch -x run
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/backend/telemetry-service/src
        - action: rebuild
          path: ./Cargo.toml
    volumes:
      - telemetry-target:/app/backend/telemetry-service/target
      - cargo-registry:/usr/local/cargo/registry

  telemetry-db:
    ports:
      - "5432:5432"

  telemetry-db-gui:
    image: sosedoff/pgweb:latest
    environment:
      - PGWEB_DATABASE_URL=postgres://telemetry:telemetry@telemetry-db:5432/telemetrydb?sslmode=disable
      - PGWEB_PREFIX=telemetry-db-gui
    depends_on:
      telemetry-db:
        condition: service_healthy

volumes:
  telemetry-target:
  cargo-registry:
