load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "api",
    srcs = [
        "handler.go",
        "internalauth.go",
    ],
    importpath = "github.com/NickGhignatti/crowd-vision/server/tenancy-service/internal/api",
    visibility = ["//server/tenancy-service:__subpackages__"],
    deps = [
        "//server/auth-middleware",
        "//server/auth-policy",
        "//server/tenancy-service/internal/service",
        "//server/tenancy-service/internal/store",
        "@com_github_go_chi_chi_v5//:chi",
    ],
)

go_test(
    name = "api_test",
    srcs = ["handler_test.go"],
    deps = [
        ":api",
        "//server/tenancy-service/internal/service",
        "//server/tenancy-service/internal/storefake",
        "@com_github_go_chi_chi_v5//:chi",
    ],
)
