services:
  notification-service:
    cpus: "3"
    build:
      context: .
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://notification-db:27017/notificationdb
      - TWIN_SERVICE_URL=http://twin-service:3000
      - KAFKA_BROKERS=kafka:9092
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    depends_on:
      notification-db:
        condition: service_started
      kafka:
        condition: service_healthy

  notification-db:
    cpus: "3"
    image: mongo:latest
    volumes:
      - notification-data:/data/db

volumes:
  notification-data:
