services:
  sensor-service:
    cpus: "2"
    build:
      context: .
    environment:
      - MONGO_URI=mongodb://sensor-db:27017/sensordb
      - FRONTEND_URL=${DEV_URL}:${FRONTEND_PORT}
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      sensor-db:
        condition: service_started
      kafka:
        condition: service_healthy

  sensor-db:
    cpus: "2"
    image: mongo:latest
    volumes:
      - sensor-data:/data/db

volumes:
  sensor-data:
