apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: crowdvision
data:
  PORT: "3000"

  REDIS_URL: "redis://redis:6379"
  KAFKA_BROKERS: "kafka:9092"
  TELEMETRY_URL: "http://telemetry:3000"
  DIGITAL_TWIN_URL: "http://digital-twin:3000"
  DASHBOARD_URL: "http://dashboard:3000"

  GATEWAY_URL: "http://crowdvision.local"
  PUBLIC_URL: "http://crowdvision.local"
  FRONTEND_URL: "http://crowdvision.local"
