include:
  - path: ../../docker/rust-base/docker-compose.yml

services:
  twin-db:
    image: mongo:8.3.9

  digital-twin-test:
    build:
      context: ../..
      dockerfile: backend/digital-twin/Dockerfile
      additional_contexts:
        rust-base: service:rust-base
      target: dev
    command: ["bash", "/app/scripts/test/rust-integration-tests.sh"]
    environment:
      - MONGO_URI=mongodb://twin-db:27017
    depends_on:
      - twin-db
