services:
  twin-db:
    image: mongo:7

  digital-twin-test:
    build:
      context: ../..
      dockerfile: backend/digital-twin/Dockerfile
      target: dev
    command: ["bash", "/app/scripts/test/rust-integration-tests.sh"]
    environment:
      - MONGO_URI=mongodb://twin-db:27017
    depends_on:
      - twin-db
