services:
  sensor-simulator:
    build: simulators/sensor-simulator
    ports:
      - "3001:3000"
    networks:
      - simulator-net
  aq-simulator:
    build: ./simulators/aq-simulator
    ports:
      - "3002:3000"
    networks:
      - simulator-net
