services:
  notification-service:
    build:
      context: .
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://notification-db:27017/notificationdb
      - GATEWAY_URL=http://gateway
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - CLIENT_URL=${DEV_URL}:${CLIENT_PORT}
    depends_on:
      - notification-db

  notification-db:
    image: mongo:latest
    volumes:
      - notification-data:/data/db

volumes:
  notification-data:
