services:
  notification-service:
    build:
      target: builder
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json

  notification-db:
    ports:
      - "27019:27017"

  notification-db-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://notification-db:27017/
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_SITE_BASEURL=/notification-db-gui/
    depends_on:
      - notification-db
