.git
node_modules
**/node_modules
**/dist
**/target
**/coverage
client
landing-page
documentation
simulators
k8s
**/*.md
.env
**/.env

# Python
**/__pycache__
**/*.pyc
**/.venv
**/.pytest_cache
**/.ruff_cache
