apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-service
  namespace: crowdvision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-service
  template:
    metadata:
      labels:
        app: sensor-service
    spec:
      containers:
        - name: sensor-service
          image: ghcr.io/nickghignatti/crowdvision-sensor:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://sensor-db:27017/sensordb"
          envFrom:
            - configMapRef:
                name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-service
  namespace: crowdvision
spec:
  selector:
    app: sensor-service
  ports:
    - port: 3000
      targetPort: 3000