services:
  redis:
    image: redis:alpine

  socket-service-test:
    build:
      context: .
      target: test
    command: ["bash", "/app/scripts/test/rust-integration-tests.sh"]
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../../scripts/test/rust-integration-tests.sh:/app/scripts/test/rust-integration-tests.sh:ro
    depends_on:
      - redis
