$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  language: 'go'

tasks:
  build:
    command: 'go build ./...'
    inputs:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

  test:
    command: 'go test ./...'
    inputs:
      - '**/*.go'
      - 'go.mod'

  # Swap to golangci-lint if/when it's adopted.
  lint:
    command: 'go vet ./...'
    inputs:
      - '**/*.go'
      - 'go.mod'

  deps:
    command: 'go mod download'
    inputs:
      - 'go.mod'
      - 'go.sum'
    options:
      cache: false
