$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  language: 'javascript'

tasks:
  deps:
    command: 'npm ci'
    inputs:
      - 'package.json'
      - 'package-lock.json'
    options:
      cache: false

  relock:
    script: 'rm -rf node_modules package-lock.json && npm install --package-lock-only --cpu=x64 --os=linux'
    options:
      cache: false
