const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const envPath = path.join(__dirname, "..", ".env");

function generateAdminSecret() {
    let envContent = "";

    // 1. Read existing .env file if it exists
    if (fs.existsSync(envPath)) {
        envContent = fs.readFileSync(envPath, "utf8");
    }

    if (envContent.includes("INTERNAL_ADMIN_SECRET=")) {
        console.log("✅ INTERNAL_ADMIN_SECRET is already present in .env. Skipping generation.");
        return;
    }

    console.log("🔑 Generating secure INTERNAL_ADMIN_SECRET...");
    const generatedSecret = crypto.randomBytes(32).toString("hex");
    const envEntry = `\n# Generated by scripts/admin.js\nINTERNAL_ADMIN_SECRET=${generatedSecret}\n`;

    if (fs.existsSync(envPath)) {
        fs.appendFileSync(envPath, envEntry);
    } else {
        fs.writeFileSync(envPath, envEntry);
    }

    console.log("✅ Secret generated and appended to .env");
    console.log("⚠️  IMPORTANT: Please RESTART your server now so it loads the new secret!");
}

generateAdminSecret();