#!/usr/bin/env bash
set -uo pipefail

cd "$(dirname "../${BASH_SOURCE[0]}")"  # repo root

export COMPOSE_BAKE=true
RUNTIME_FILE="compose.runtime.yml"

# ── Parse flags ──────────────────────────────────────────────────────────────
# Each flag names literal compose service names to leave out of `up`'s
# explicit service list — not a folder-exclude or profile tag, so adding a
# future --no-X flag is just adding a new entry here.

declare -A EXCLUDE_GROUPS=(
  [agent]="agent-service agent-db agent-ingester redis-langfuse langfuse-web langfuse-worker langfuse-db clickhouse minio"
  [metrics]="prometheus grafana"
  [simulators]="aq-simulator sensor-simulator"
)

excluded=()
dry_run=false
for arg in "$@"; do
  case "$arg" in
    --no-agent) excluded+=(${EXCLUDE_GROUPS[agent]}) ;;
    --no-metrics) excluded+=(${EXCLUDE_GROUPS[metrics]}) ;;
    --no-simulators) excluded+=(${EXCLUDE_GROUPS[simulators]}) ;;
    --dry-run) dry_run=true ;;
    *)
      echo "Unknown flag: $arg" >&2
      echo "Usage: $0 [--no-agent] [--no-metrics] [--dry-run]" >&2
      exit 1
      ;;
  esac
done

# ── Build the include list (root + backend/*/ + simulators/*/ + frontend/) ──
# Each include entry is one or two files: a folder's own docker-compose.yml,
# plus its docker-compose.dev.yml if present (hot-reload overlay). Grouped
# entries can't share a service across separate `include:` items ("conflicts
# with imported resource"), so base+dev must be one entry, not two.

includes=()      # YAML-ready: "path" or "path1|path2" (merged entry)
all_files=()     # flat, for the container_name grep below

add_service() {
  local folder="$1"
  local base="$folder/docker-compose.yml"
  local dev="$folder/docker-compose.dev.yml"
  [ -f "$base" ] || return
  all_files+=("$base")
  if [ -f "$dev" ]; then
    all_files+=("$dev")
    includes+=("$base|$dev")
  else
    includes+=("$base")
  fi
}

includes+=("docker-compose.yml")
all_files+=("docker-compose.yml")

for dir in backend/*/; do
  folder="${dir%/}"
  [ "$folder" = "backend/tests" ] && continue
  add_service "$folder"
done

for dir in simulators/*/; do
  add_service "${dir%/}"
done

add_service "frontend"

# ── Write compose.runtime.yml ────────────────────────────────────────────────

{
  echo "# Auto-generated by stack.sh — do not commit."
  echo "# Re-generated every time ./stack.sh runs."
  echo "include:"
  for entry in "${includes[@]}"; do
    if [[ "$entry" == *"|"* ]]; then
      echo "  - path:"
      IFS='|' read -ra parts <<< "$entry"
      for p in "${parts[@]}"; do
        echo "      - $p"
      done
    else
      echo "  - path: $entry"
    fi
  done
} > "$RUNTIME_FILE"

echo "Generated $RUNTIME_FILE with ${#includes[@]} includes."

# ── Clear stray fixed-name containers ────────────────────────────────────────
# A pinned container_name orphaned by an interrupted run name-clashes the next
# `up` (no compose project label to reconcile it) — force-remove non-running
# matches. container_name values come straight from the source YAML (always
# literal strings in this repo) — no docker/jq JSON parsing needed for this.

mapfile -t pinned_names < <(
  grep -h '^\s*container_name:' "${all_files[@]}" 2>/dev/null \
    | sed -E 's/^\s*container_name:\s*//; s/["'"'"']//g'
)

if [ ${#pinned_names[@]} -gt 0 ]; then
  while IFS=$'\t' read -r name state; do
    for pinned in "${pinned_names[@]}"; do
      if [ "$name" = "$pinned" ] && [ "$state" != "running" ]; then
        echo "Removing stray container: $name"
        docker rm -f "$name" >/dev/null
      fi
    done
  done < <(docker ps -a --format '{{.Names}}\t{{.State}}')
fi

# ── Apply exclusion flags + run ──────────────────────────────────────────────

up_args=(compose -f "$RUNTIME_FILE" up --watch --remove-orphans --build)

if [ ${#excluded[@]} -gt 0 ]; then
  mapfile -t all_services < <(docker compose -f "$RUNTIME_FILE" config --services)
  included=()
  for service in "${all_services[@]}"; do
    keep=true
    for excl in "${excluded[@]}"; do
      [ "$service" = "$excl" ] && keep=false && break
    done
    $keep && included+=("$service")
  done
  echo "Excluding: ${excluded[*]}"
  up_args+=("${included[@]}")
fi

if $dry_run; then
  echo "docker ${up_args[*]}"
  exit 0
fi

exec docker "${up_args[@]}"
