name: CI Go Services
on:
  push:
    branches-ignore: [master]
    paths:
      - 'server/auth-contracts/**'
      - 'server/auth-middleware/**'
      - 'server/auth-policy/**'
      - 'server/provisioner/**'
      - 'server/claims-gateway/**'
      - 'server/registry-service/**'
      - 'server/tenancy-service/**'
  workflow_call:

jobs:
  discover:
      uses: ./.github/workflows/templates/discovery.yml
      with:
        services_json: >
          [
            { key: auth-contracts, dir: server/auth-contracts, builds_binary: false },
            { key: auth-middleware, dir: server/auth-middleware, builds_binary: false },
            { key: auth-policy, dir: server/auth-policy, builds_binary: false },
            { key: claims-gateway, dir: server/claims-gateway, builds_binary: true },
            { key: provisioner, dir: server/provisioner, builds_binary: true },
            { key: registry-service, dir: server/registry-service, builds_binary: true },
            { key: tenancy-service, dir: server/tenancy-service, builds_binary: true }
          ]

  run-ci:
      needs: discover
      if: ${{ needs.discover.outputs.is_empty == 'false' }}
      strategy:
        fail-fast: false
        matrix:
          include: ${{ fromJson(needs.discover.outputs.matrix) }}

      uses: ./.github/workflows/templates/go/ci.yml
      with:
        service_key: ${{ matrix.key }}
        working_directory: ${{ matrix.dir }}
        builds_binary: ${{ matrix.builds_binary }}
