name: socket-service-ci

on:
  workflow_call:

jobs:
  socket-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server/socket-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build
        run: npm run build

      - name: 🧪 Run Server Tests
        run: npm run test
        continue-on-error: false
