name: CI Simulators

on:
  workflow_call:

jobs:
  node-simulators:
    name: sensor-simulator
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./simulators/sensor-simulator
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup-node
        with:
          working_directory: ./simulators/sensor-simulator
          needs_shared_eslint: 'true'

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  python-simulators:
    name: aq-simulator
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./simulators/aq-simulator
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.12"

      - name: Syntax Check (py_compile)
        run: find . -name '*.py' -print0 | xargs -0 python -m py_compile

      - name: Install Ruff
        run: pip install ruff

      - name: Lint (ruff)
        run: ruff check .
