name: CI Simulators

on:
  workflow_call:

jobs:
  node-simulators:
    name: sensor-simulator
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./simulators/sensor-simulator
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup-node
        with:
          working_directory: ./simulators/sensor-simulator
          needs_shared_eslint: "true"

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm test

  python-simulators:
    name: aq-simulator
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./simulators/aq-simulator
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup-python
        with:
          working_directory: ./simulators/aq-simulator

      - name: Lint
        run: uv run ruff check .

      - name: Type Check
        run: uv run pyright

      - name: Audit Dependencies
        run: uv audit

      - name: Run Tests
        run: uv run pytest

  python-simulators-ap:
    name: ap-simulator
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./simulators/ap-simulator
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup-python
        with:
          working_directory: ./simulators/ap-simulator

      - name: Lint
        run: uv run ruff check .

      - name: Type Check
        run: uv run pyright

      - name: Audit Dependencies
        run: uv audit

      - name: Smoke test
        run: uv run python smoke.py
