name: documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'documentation/**'
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'documentation/**'

permissions:
  contents: write

jobs:
  build-documentation:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: quarkdown-labs/setup-quarkdown@v1

      - name: Build user docs
        run: quarkdown c documentation/user/main.qd --out landing-page/user

      - name: Build dev docs
        run: quarkdown c documentation/developer/main.qd --out landing-page/dev

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./landing-page
          force_orphan: true
