name: Cleanup Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0"

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-name:
          # Backend microservices
          - crowdvision-agent
          - crowdvision-chat
          - crowdvision-claims-gateway
          - crowdvision-contracts
          - crowdvision-notification
          - crowdvision-provisioner
          - crowdvision-registry
          - crowdvision-sensor
          - crowdvision-socket
          - crowdvision-tenancy
          - crowdvision-twin
          # Frontend
          - crowdvision-client
          # Simulators
          - crowdvision-simulator
          - crowdvision-aq-simulator

    steps:
      - name: Delete old package versions for ${{ matrix.package-name }}
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: ${{ matrix.package-name }}
          package-type: "container"
          min-versions-to-keep: 3
          ignore-versions: "latest"
