name: Renovate

on:
  workflow_dispatch: # allow a manual run any time
  schedule:
    - cron: "0 2 * * 1" # Weekly at 2AM UTC on Monday

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
