name: Python CI Template
on:
  workflow_call:
    inputs:
      service_key:
        required: true
        type: string
      working_directory:
        required: true
        type: string

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup-python
        with:
          working_directory: ${{ inputs.working_directory }}

      - name: Lint
        run: uv run ruff check .

      - name: Check Formatting
        run: uv run ruff format --check .

      - name: Type Check
        run: uv run pyright

      - name: Audit Dependencies
        run: uv audit

      - name: Run Tests
        run: uv run pytest
